package com.glam.twig.parser;

public enum JSONParserType {
	IPPINLIST, PROFILE, USERLIST, FOLLOWING, FOLLOW, UNFOLLOW, FRIENDS, IPPINDETAIL, 
	FOURSQUAREVENUE, ADDPHOTO, RESTDETAIL, TIMELINEFOLLOWING, RESTAURANTDETAILS, IPPINATE, IPPINCATEGORIES, IPPINBROWSECATEGORY,
	IPPINBLOGS, PROFILEFOLLOW
}
