package com.glam.twig;

public enum ActionTypes {
	HOME, MENTION, MESSAGE, LIST, MORE, COMPOSE, MESSAGECONVERSATION, REPLYCONVERSATION, 
	HASH, USER, LISTFOLLOWING, LISTFOLLOWERS, LISTTWEET, PROFILEADD, 
	PROFILE, PROFILEFAVORITE, PROFILEFOLLOWERS, PROFILEFOLLOWINGS, PROFILELIST, RETWEETBYYOU, RETWEETFORYOU, RETWEETYOU,
	SAVESEARCH, SEARCH, SEARCHTWEET, TRENADS, TREANDSAVAILABLE, THEME, THEMEPRIVIEW, WEBVIEW, USERLIST, USERTWEET
}
